### PR TITLE
add release notes for 2.6 query workbench

### PR DESCRIPTION
**Pull request by derek-ho**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by joshuali925 — APPROVED** [review]

**Review by pjfitzgibbons — APPROVED** [review]

**Review by mengweieric — APPROVED** [review]

**Review by YANG-DB — APPROVED** [review]

**Comment by ps48** [comment]
@derek-ho can you please check the test failure.

**Comment by dai-chen** [comment]
Not sure if related to the failure. There seems a new PR merged this morning: https://github.com/opensearch-project/dashboards-query-workbench/pull/46

**Comment by derek-ho** [comment]
I dont think this PR touches an dependencies, shouldn't cause what I'm seeing on the CI. Restarted the build but will check a few more things

**Comment by dai-chen** [comment]
> I dont think this PR touches any dependencies, shouldn't cause what I'm seeing on the CI. Restarted the build but will check a few more things

okay. then should I include it in the release notes?

**Review by dai-chen — APPROVED** [review]

**Pull request merged**
