### PR TITLE
Sync dependencies to the latest versions

### PR DESCRIPTION
**Pull request by RyanL1997**
### Description
Due to the failure of version conflict for security dashboards plugin's distribution build: https://github.com/opensearch-project/security-dashboards-plugin/blob/7cad47c38478646cd96f0eb1623b77acd853b803/package.json#L30
 
### Issues Resolved
* Relate https://github.com/opensearch-project/dashboards-query-workbench/issues/240 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by derek-ho — APPROVED** [review]
Thanks!

**Comment by derek-ho** [comment]
Why is snapshot failing?

**Comment by RyanL1997** [comment]
@derek-ho I have updated the snapshot by running `yarn run test:jest -u` but im not sure if  we should do that.. cc @ps48

**Comment by RyanL1997** [comment]
For reference, the snapshots test would fail like this: https://github.com/opensearch-project/dashboards-query-workbench/actions/runs/7452711838/job/20276572778?pr=241#step:5:328 without the update

**Review by Swiddis — APPROVED** [review]
Snapshot updates look like they're checking loaded components now instead of loading ones. I checked the tests and it doesn't look like any of these should be on a loading component, so I'm wondering why the snapshot was made with a loading state at all. This seems like maybe a silent rendering bugfix with the react update? Poked around the changelog and didn't see any obvious candidates.

I'm inclined to merge this if there's not a clear reason we need the components to remain loading in the snapshot.

**Review by ps48 — COMMENTED** [review]
@RyanL1997 Can you please add the backport label to 2.x?

**Review by ps48 — APPROVED** [review]

**Comment by RyanL1997** [comment]
I will manually backport this

**Pull request merged**
